#!/usr/bin/env bash
# =====================================================================
# Azure AI Search Workshop - 원클릭 배포 스크립트
# 사용법:
#   ./deploy.sh <suffix> [resource-group] [rg-location]
# 예시:
#   ./deploy.sh 260114-changjuahn
#   ./deploy.sh 260114-changjuahn rg-aisearch-260114-changjuahn koreacentral
# =====================================================================
set -euo pipefail

SUFFIX="${1:?suffix 인자가 필요합니다. 예: ./deploy.sh 260114-changjuahn}"
RG="${2:-rg-aisearch-${SUFFIX}}"
RG_LOCATION="${3:-koreacentral}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

echo "▶ 리소스 그룹 확인/생성: ${RG} (${RG_LOCATION})"
az group create --name "${RG}" --location "${RG_LOCATION}" --output none

DEPLOYMENT_NAME="aisearch-workshop-$(date +%Y%m%d%H%M%S)"

echo "▶ Bicep 배포 시작: ${DEPLOYMENT_NAME}"
az deployment group create \
  --name "${DEPLOYMENT_NAME}" \
  --resource-group "${RG}" \
  --template-file "${SCRIPT_DIR}/main.bicep" \
  --parameters suffix="${SUFFIX}" \
  --output none

echo "▶ 배포 출력값 조회"
OUTPUTS=$(az deployment group show \
  --name "${DEPLOYMENT_NAME}" \
  --resource-group "${RG}" \
  --query properties.outputs \
  --output json)

SEARCH_NAME=$(echo "${OUTPUTS}" | jq -r '.searchName.value')
SEARCH_ENDPOINT=$(echo "${OUTPUTS}" | jq -r '.searchEndpoint.value')
FOUNDRY_NAME=$(echo "${OUTPUTS}" | jq -r '.foundryName.value')
OPENAI_ENDPOINT=$(echo "${OUTPUTS}" | jq -r '.openAIEndpoint.value')
PROJECT_ENDPOINT=$(echo "${OUTPUTS}" | jq -r '.projectEndpoint.value')
CHAT_DEPLOY=$(echo "${OUTPUTS}" | jq -r '.chatDeploymentName.value')
EMB_DEPLOY=$(echo "${OUTPUTS}" | jq -r '.embeddingDeploymentName.value')

echo "▶ API 키 조회"
SEARCH_KEY=$(az search admin-key show --service-name "${SEARCH_NAME}" --resource-group "${RG}" --query primaryKey -o tsv)
OPENAI_KEY=$(az cognitiveservices account keys list --name "${FOUNDRY_NAME}" --resource-group "${RG}" --query key1 -o tsv)

ENV_FILE="${REPO_ROOT}/.env"
echo "▶ .env 파일 작성: ${ENV_FILE}"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by 01-setup/infra/deploy.sh on $(date)
# Azure AI Search
SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
SEARCH_ADMIN_KEY=${SEARCH_KEY}
SEARCH_INDEX_NAME=products-index

# Azure OpenAI (Foundry)
AZURE_OPEN_AI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPEN_AI_KEY=${OPENAI_KEY}
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${EMB_DEPLOY}
AZURE_OPENAI_CHAT_DEPLOYMENT=${CHAT_DEPLOY}
AZURE_OPENAI_API_VERSION=2024-02-01

# Foundry Project (Agentic Retrieval 등에 사용)
AZURE_AI_PROJECT_ENDPOINT=${PROJECT_ENDPOINT}
EOF

echo ""
echo "✅ 배포 완료"
echo "   - Search:  ${SEARCH_ENDPOINT}"
echo "   - OpenAI:  ${OPENAI_ENDPOINT}"
echo "   - Project: ${PROJECT_ENDPOINT}"
echo "   - .env:    ${ENV_FILE}"
